name: hermit-action
description: 'Runs Hermit Conformance Check'
branding:
  icon: 'crosshair'
  color: 'purple'
inputs:
    hermit-param:
      description: 'Hermit param'
      required: true
      default: 'some default param'
runs:
    using: 'docker'
    image: 'vikiss/mystery-utils:latest'
    args:
      - ${{ inputs.hermit-param }}
