name: hermit-action
description: 'Runs Hermit Conformance Check'
branding:
  icon: 'crosshair'
  color: 'purple'
inputs:
    target-url:
      description: 'Target URL to scan'
      required: true
      default: 'https://hermit-service'
    show-config:
      description: 'Print Hermit config'
      required: false
      default: ''
    api-key:
      description: 'Hermit API Key'
      required: true
      default: ''
runs:
    using: 'docker'
    image: 'ghcr.io/vikiss/hermit:latest'
    args:
      - 'analyze'
      - "--api-key=${{ inputs.api-key }}"
      - "--label=githubAction"
      - "--target-url=${{ inputs.target-url }}"
      - ${{ inputs.show-config }}
