targets:
  - "api": "eeeeeeee-ffff-cccc-dddd-aaaaabbbbbbb"
    "url": "http://localhost:3000/"
    "definition":
      "type": "API_KIND_OPENAPI"
      "file": "swagger.yaml"

labels:
  env: "dev"

analysis:
  platformURL: "http://api-alpha.cieri.ai"
  timeLimit: "15m"
  analyzers:
    - "OpenAPIConformance"
    - "BOLA"
    - "BUA"
    - "ExcessiveDataExposure"
    - "ServerError"
